# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=TPPSim02_FMU_tests_FMU_test1 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"     -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined 
DIREXTRA=-L"/TPPSim02/FMU_tests"
MAINFILE=TPPSim02.FMU_tests.FMU_test1.c
MAINOBJ=TPPSim02.FMU_tests.FMU_test1.o
CFILES=TPPSim02.FMU_tests.FMU_test1_functions.c TPPSim02.FMU_tests.FMU_test1_records.c \
TPPSim02.FMU_tests.FMU_test1_01exo.c TPPSim02.FMU_tests.FMU_test1_02nls.c TPPSim02.FMU_tests.FMU_test1_03lsy.c TPPSim02.FMU_tests.FMU_test1_04set.c TPPSim02.FMU_tests.FMU_test1_05evt.c TPPSim02.FMU_tests.FMU_test1_06inz.c TPPSim02.FMU_tests.FMU_test1_07dly.c \
TPPSim02.FMU_tests.FMU_test1_08bnd.c TPPSim02.FMU_tests.FMU_test1_09alg.c TPPSim02.FMU_tests.FMU_test1_10asr.c TPPSim02.FMU_tests.FMU_test1_11mix.c TPPSim02.FMU_tests.FMU_test1_12jac.c TPPSim02.FMU_tests.FMU_test1_13opt.c TPPSim02.FMU_tests.FMU_test1_14lnz.c \
TPPSim02.FMU_tests.FMU_test1_15syn.c TPPSim02.FMU_tests.FMU_test1_16dae.c TPPSim02.FMU_tests.FMU_test1_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) TPPSim02.FMU_tests.FMU_test1.makefile TPPSim02.FMU_tests.FMU_test1_literals.h TPPSim02.FMU_tests.FMU_test1_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that TPPSim02.FMU_tests.FMU_test1_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) TPPSim02.FMU_tests.FMU_test1_functions.h TPPSim02.FMU_tests.FMU_test1_literals.h $(OFILES)
	$(CC) -I. -o TPPSim02.FMU_tests.FMU_test1$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f TPPSim02.FMU_tests.FMU_test1_records.o $(MAINOBJ)

bundle:
	@tar -cvf TPPSim02.FMU_tests.FMU_test1_Files.tar $(GENERATEDFILES)