/* Additional record code for TPPSim02.FMU_tests.FMU_test1 generated by the OpenModelica Compiler OpenModelica 1.15.0~dev-49-gb315f0e. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "TPPSim02.FMU_tests.FMU_test1_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

