version: "3"
services:
  openmodelica:
    image: openmodelica
    build:
      context: .
      dockerfile: Dockerfile.om
    volumes:
      - ./TPPSim02:/TPPSim02
  omsimulator:
    image: omsimulator
    build:
      context: .
      dockerfile: Dockerfile.oms
    volumes:
      - ./TPPSim02:/TPPSim02
