version: "3.8"
services:
  openmodelica:
    image: openmodelica
    build:
      context: .
      dockerfile: Dockerfile.om
    volumes:
      - ./TPPSim02:/TPPSim02
  omsimulator:
    image: omsimulator
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 16G
    build:
      context: .
      dockerfile: Dockerfile.oms
    volumes:
      - ./TPPSim02:/TPPSim02
  ompython:
    image: ompython
    build:
      context: .
      dockerfile: Dockerfile.omp
    volumes:
      - ./TPPSim02:/TPPSim02
  opc1:
    image: opc1
    ports:
      - "4841:4841"
    build:
      context: .
      dockerfile: Dockerfile.opc1
    volumes:
      - ./TPPSim02:/TPPSim02
