# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=TPPSim02_Pipes_Tests_PipeChannelFMU_Test -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=16 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"     -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined 
DIREXTRA=-L"/TPPSim02/Pipes/Tests"
MAINFILE=TPPSim02.Pipes.Tests.PipeChannelFMU_Test.c
MAINOBJ=TPPSim02.Pipes.Tests.PipeChannelFMU_Test.o
CFILES=TPPSim02.Pipes.Tests.PipeChannelFMU_Test_functions.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_records.c \
TPPSim02.Pipes.Tests.PipeChannelFMU_Test_01exo.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_02nls.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_03lsy.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_04set.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_05evt.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_06inz.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_07dly.c \
TPPSim02.Pipes.Tests.PipeChannelFMU_Test_08bnd.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_09alg.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_10asr.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_11mix.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_12jac.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_13opt.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_14lnz.c \
TPPSim02.Pipes.Tests.PipeChannelFMU_Test_15syn.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_16dae.c TPPSim02.Pipes.Tests.PipeChannelFMU_Test_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) TPPSim02.Pipes.Tests.PipeChannelFMU_Test.makefile TPPSim02.Pipes.Tests.PipeChannelFMU_Test_literals.h TPPSim02.Pipes.Tests.PipeChannelFMU_Test_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that TPPSim02.Pipes.Tests.PipeChannelFMU_Test_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) TPPSim02.Pipes.Tests.PipeChannelFMU_Test_functions.h TPPSim02.Pipes.Tests.PipeChannelFMU_Test_literals.h $(OFILES)
	$(CC) -I. -o TPPSim02.Pipes.Tests.PipeChannelFMU_Test$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/root/.openmodelica/binaries/Modelica" -Wl,-rpath="/root/.openmodelica/binaries/Modelica" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/x86_64-linux" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library/linux64" "-L/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.2/Resources/Library" -lModelicaExternalC $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f TPPSim02.Pipes.Tests.PipeChannelFMU_Test_records.o $(MAINOBJ)

bundle:
	@tar -cvf TPPSim02.Pipes.Tests.PipeChannelFMU_Test_Files.tar $(GENERATEDFILES)